POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1YW5oeSIsImlkIjo2LCJpYXQiOjE2Nzc1MTE2MzF9.QjV1SLL0cg318F_jEACBo-nrbkOPYXES9S6mK89HhC4

{
    "author": "juanhy",
    "url": "http://test.test",
    "title": "Test Blog"
}