DELETE http://localhost:3001/api/blogs/34
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1YW5oeSIsImlkIjo2LCJpYXQiOjE2Nzc1NjQwNTd9.nVwGBTYat_mdzU115ocN0PQiotTf2JddnyMdt3nM7aQ